ALTER TABLE "Order" ADD COLUMN "cargoCompany" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "trackingNo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "trackingUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Order" ADD COLUMN "shippedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN "deliveredAt" TIMESTAMP(3);
